# Automatically generated by `update-cbn.scm`. DO NOT EDIT!
{ cataclysmBN, common }:

rec {
  latest = b993;
  b993 = let
    args = {
      version = "993";
      rev = "ec9d549929680ef655faa13e668c6168ac299810";
      sha256 = "19vp9gdkkpjzdydwbpj7vj8agdfa28wcv12rb5zgrd6kxw8j3w0k";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b972 = let
    args = {
      version = "972";
      rev = "bbd2a5d3b7e4a03614e93b68e29f25ee6501178a";
      sha256 = "1lilyw596kmj2yfmq4p28jz2rwwczi34d558ni30xz0791vbjbcc";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b971 = let
    args = {
      version = "971";
      rev = "ffbd9d845527461c2da801faffe72f4001214e1a";
      sha256 = "0d5a7zi5hnlyji8hs7qymr0zbl73bacgapvm6fwpiiz32vmhwng7";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b961 = let
    args = {
      version = "961";
      rev = "de8c5f099647bacfd30af12d4e97c2d511d92531";
      sha256 = "16l6771rc7ja3vk5vxl9kphp522n5yj9rsqa6wh9ijlr069prvvb";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b907 = let
    args = {
      version = "907";
      rev = "7aae68a219b2bc3392aa32b34874cdc669e22aae";
      sha256 = "0rb3dhviag9an6mln69k0gdr13214za764rj5kn74933hgkr1dxy";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b906 = let
    args = {
      version = "906";
      rev = "5d50a8058151c8221cd777cbaa1c8f2466d5f032";
      sha256 = "1yhp2sj1ng08knkk7rv51rgz4r84p9ydzwd68b17wmf2is8sn51a";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b905 = let
    args = {
      version = "905";
      rev = "381c192e1dad62cee240b2fbf945a61c4ed89608";
      sha256 = "0mdqzjyxxvv7nfm7nhykj9pzl6kvymk04lqg0ajml01qj2fpfhh2";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b901 = let
    args = {
      version = "901";
      rev = "5d73cdc066bc27c45e41dfec5c734f0a8dde6f39";
      sha256 = "19p9r112wj4rfxyp33sn8v98436wq1n38q0vxjwk0ysqsgxx9brz";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b891 = let
    args = {
      version = "891";
      rev = "dd73e8e5c48a2ba109556cc800be924a44dd0e79";
      sha256 = "13lnp0gx037b16qccpkiffma2835xa7hmsf549l8dny1xq6j817x";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b890 = let
    args = {
      version = "890";
      rev = "5619c69b1d44d8c2aeedf08a75cb0669833aee01";
      sha256 = "08dbvblva978lzh1ypcb9jybdkzcw5k2nm1g2y0yn04qmb6d5vdm";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b881 = let
    args = {
      version = "881";
      rev = "ac96200b0aa9a4e437fcd5bf64a93c0ae09a1f04";
      sha256 = "1fih637mxvkcqm63dzhvxlx0bzj1c302ixgpjnw4xlmni5wbbkyy";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b871 = let
    args = {
      version = "871";
      rev = "f3a475288623302ee4731e181d273eddd5614a5d";
      sha256 = "0mra9i81x0vymhc9zn0vwa53sclzq3mcv994163pix4bhj6hp8kp";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b870 = let
    args = {
      version = "870";
      rev = "04a4a0804774df47e735f465c4376bbf1b633fe2";
      sha256 = "1y05qkd5j26f58svbbq3blc0bm8vq93rhyk1rdry4y0fc7pp5r90";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b869 = let
    args = {
      version = "869";
      rev = "3cd5c8dedb1d8e74335038f0f28f2c4520768761";
      sha256 = "14rdrwy9m1fmr855sdgmp6l2jma0wbqhbl0c1c7fqgpxdjp2ki5m";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b865 = let
    args = {
      version = "865";
      rev = "a45b5a375d5ae3f3cc2665d840b2e4871244cfa8";
      sha256 = "1xcwq9241fnd32p30wj2347f668qbhjklhp46qazsmcjgk96rrph";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b858 = let
    args = {
      version = "858";
      rev = "2676780a4c2d7724995f2870ac3f202a14fd0bc5";
      sha256 = "15xl2ysmni0nwqi45mc972h2xah7j92z1ryw4wpxrinvwyakxadq";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b856 = let
    args = {
      version = "856";
      rev = "440a4bdb728ceab24c863254c515f113513bc8d2";
      sha256 = "16hdkka0sg5ajphhyyfid20hzhjqhygm81brn4xn1bcqz3gd3a0b";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b846 = let
    args = {
      version = "846";
      rev = "7da6104589b5cb117ec7ab84935121a3a1839421";
      sha256 = "0zrrv0hc2p7r6d4gnq68vaf8g1dmq0s8imhy6czksm16w3sk9wd5";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b840 = let
    args = {
      version = "840";
      rev = "c285cff223b0340b9b4fcd200198118581800360";
      sha256 = "0b486h3qcgn90fc9wqq5is3pk8g9q43kgc1p152zvy0wfy2dczln";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b839 = let
    args = {
      version = "839";
      rev = "aa4e2d063394b6972f75239d1adbdaf9f5ab9298";
      sha256 = "0dvwfidgidlk1hb63l5d33wvmc2b7zakcmkk3137jkz7avahmfhx";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b837 = let
    args = {
      version = "837";
      rev = "98a457b7fff6097cc9bfc5e016f85b3a29492b15";
      sha256 = "1g6a2jyj83gv75wmjxfdj97hxvk439ihijpvf7aa4bw25zk8m85c";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b833 = let
    args = {
      version = "833";
      rev = "a9327e925df1d725b07cd77cc997eb7497cc5177";
      sha256 = "0w4kvsaxy6kdqnfiw42rhymy22m9p4zjzm7c1mr8sh84sl3n6rk8";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b832 = let
    args = {
      version = "832";
      rev = "9c3653158d38f76770f085f108174e1495c99fed";
      sha256 = "01nqyfa13q1p7jb90b7piwih3zgqjn84l7gkf5bpw796j7kgzd5j";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b826 = let
    args = {
      version = "826";
      rev = "2bd90b4a159fa7745f9ab8706dc76ee4978bf9f8";
      sha256 = "1r366ghq0hmrkvig49v4iy39zp1bdql4aakb4lwhprywfy5pfv9w";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b825 = let
    args = {
      version = "825";
      rev = "4c6dd989409843b200a1db47dd2a2aaf788935c3";
      sha256 = "1v1fdkq42l91a9xfwbz60mzamfy4j6whc8qd5svi8aiifq5cxxbg";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b821 = let
    args = {
      version = "821";
      rev = "2e985739900fe4baf03652821b22e07e508f50ad";
      sha256 = "1g4si1q84j931lhccprayx6f4dlh5aqmkvqmcp6cw4z3fipcyvr8";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b760 = let
    args = {
      version = "760";
      rev = "2f0a81794d8a2d12b23eac6e209cb13ed5ccc193";
      sha256 = "0mwj3ky1wlvsi9v6kkn1rzlii02zxspzb6g4896fh4fbpnmdpk8m";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b735 = let
    args = {
      version = "735";
      rev = "0d5e8f40ef5f564004a2786b3354976e7205d75e";
      sha256 = "1jxdrz3ir19scvk0kyn5cyz4rwpphgq4yghkd6rkh0yx9ccway9l";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b734 = let
    args = {
      version = "734";
      rev = "f6ad86be98c73dc18ba3f251bdd607117d5aa9a1";
      sha256 = "15ycrysakv3q3ffbyks35rxasg66cj8lfi6k3806mkf7hamijlq0";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b728 = let
    args = {
      version = "728";
      rev = "19994b55bcc519da010fc9d38468ec92e65a8b82";
      sha256 = "1ls9s0vcbm48lck08vcybg2amkkhrf8y2v11gar268pyyq2wchsl";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b703 = let
    args = {
      version = "703";
      rev = "dbd818236acb45b6ee6d3c75f98f3e33eceece62";
      sha256 = "13r0x168il781x9y5w3wbka3m4hzmzqlz83z445fmr1jagh87bsr";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b702 = let
    args = {
      version = "702";
      rev = "d1beec8c46cb7b25194641d1af414498e10d44a2";
      sha256 = "0cwk7fx6i0adr9sdmmcl99pdw302kbp7i4mavh5wwv63f9ykv31n";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b700 = let
    args = {
      version = "700";
      rev = "2f51b85caa2c93f6023c893df8c981e59bfd20b5";
      sha256 = "11aszfi7r3sbqy6ynqy45kav750ld1gasb4qb0aj2n5h43ldr5xl";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b697 = let
    args = {
      version = "697";
      rev = "712b9c72c1fbe9b52b4be3cad876f5da4671200c";
      sha256 = "1s0rixsi2mcxda1cf4s2l39qy5km4wy98fhdjx8bk3xk1ayyxr6n";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b691 = let
    args = {
      version = "691";
      rev = "53a609fcb126121cb3c475d55e6f9f9ec96bb0a8";
      sha256 = "0fpv1r72cv897pnap3m1a380fwl44ql7s4wsm0pxjv77cshykd5i";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b631 = let
    args = {
      version = "631";
      rev = "393ff85188814154d8f6c55f8e8f4670808e8702";
      sha256 = "0ff8mpzi75axv7kgk6ccaqasiszldfbrh6n15rfppzl8m3a9153g";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b625 = let
    args = {
      version = "625";
      rev = "6ff0a54ee2b5c691e6d95495496b0e8ccc7cfa77";
      sha256 = "1a6iins93wwr7g9rrbjgxxknswr3j8kwkx49bvzq2c3dwlbbni88";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b618 = let
    args = {
      version = "618";
      rev = "bee744c33906ea04828f724ea3c00b91d443191b";
      sha256 = "1jab1f8za39c58dx6rkfvd70xlh2bcbmgsga5l0969wy7igfb8c3";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b614 = let
    args = {
      version = "614";
      rev = "35bd17f00e6f92807c1dde0bfc933763bd1852e5";
      sha256 = "0qqcsy7cch6pl1d87vblhc93cfapx5vrmzl26q4wgzh6aqinxqpv";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b603 = let
    args = {
      version = "603";
      rev = "1ab150f09f122789341912d90a31c66dbd811fac";
      sha256 = "1q9xxcrw05035vd6mn2brcpi8nsnsb09aaygaw49mih3wfrd4gfj";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b602 = let
    args = {
      version = "602";
      rev = "a9bd32cc75780f8144c8611dd26f3242e350bb60";
      sha256 = "1msq4rzvx20xn8gciffwbj5l71qdy97mwqrzc546ma8vp6xn84ys";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b601 = let
    args = {
      version = "601";
      rev = "a5f31bdfee34f8d4fc0546843ce1d847a5d3ca65";
      sha256 = "151fx7yik32ai0m0gfskkkys8v27rfiy65fkbxv70ffzydcnkvm9";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b596 = let
    args = {
      version = "596";
      rev = "6f005192c2488ea50ea4a42d948d6a4386dc1693";
      sha256 = "09jpjr6qq8mapz2xwznvqg10y0v98msxiyxdb54anqydviyin4g7";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b595 = let
    args = {
      version = "595";
      rev = "3a9b01e09508086df2363618bbec8a67f0df9986";
      sha256 = "1la30n5kz0k96gj40yf87yaqahnyc5lff5jhh48rks2drgbvm9w8";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b592 = let
    args = {
      version = "592";
      rev = "f8bc4d88ea8c8b915524c6eefc67a9b3453b1d9c";
      sha256 = "0j1sqy6wn9jrckalcz2fzgrcky0yz7my6nhac7q3qrlb9qkqxhsn";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b587 = let
    args = {
      version = "587";
      rev = "130d0cdaf4fe4698a32bd038ebd44424616d784c";
      sha256 = "132bjcnxvm89g0flpyldrkn8zl8nyky5b8khjakcs70piydnghfv";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b570 = let
    args = {
      version = "570";
      rev = "0bd599fcdd6130744e7efc7197f470fd6a4f7cac";
      sha256 = "1qk81ia7c52nmla7xbxhcswbxxwqipkc9ad6kq8b1rj996ni231a";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b569 = let
    args = {
      version = "569";
      rev = "f387fb6022d5d62af5a7d6be35ab97091cbd8982";
      sha256 = "1yanndsl1rycm9b5hqvw9i5x3nrmxxk5sqj7c12qpxrr0q3i0xp0";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b568 = let
    args = {
      version = "568";
      rev = "cf8d897687a5496fc732341c560dc8bf8c310058";
      sha256 = "0idqhqakfp507lr57wx0bl5fpd5z8cdrqhv4idk5g1llfjy2pzi9";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b562 = let
    args = {
      version = "562";
      rev = "f9f9d1ad8b6279610bf77285a6372d9335e0799d";
      sha256 = "04py5vi9r6vwmlr1xpywygrdyfmj6qmc6h4x5n3r9g50h0qcica5";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b559 = let
    args = {
      version = "559";
      rev = "7379d2869786114529a52c57b1d38b5b73334266";
      sha256 = "0ncx63ng0qfzcvvxcw6avx207fpcvxi8dsf43l1ar2vp3f7cs3n7";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b558 = let
    args = {
      version = "558";
      rev = "44aa6dc80e1b22e9b9187315be6ec647da0e2bed";
      sha256 = "0wzddlpj8nci8csb92xn97bnz29np7f796ylb2rlg3kla7b926ww";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b557 = let
    args = {
      version = "557";
      rev = "e914aaf09fee9074922d46394253a7601f1ea121";
      sha256 = "091fwgmny1w5a7bczkv6c6x4n3lvzf84j6zpapvh28lc68rkqjw3";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b550 = let
    args = {
      version = "550";
      rev = "35d98f8275c930ad121e4c9f0baf59bf00238a43";
      sha256 = "0p654iz4wsdwka28fycp71by592gjr1l6cya01avsq1v1vvbbxf3";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b537 = let
    args = {
      version = "537";
      rev = "c8f463e0fe1a0456f3be45bdad58df08a4c17154";
      sha256 = "1435asabcijbshp4mafcpqpbhn1vlp3h8vkkpir56vmnsrg48c2g";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b536 = let
    args = {
      version = "536";
      rev = "e3e6881ba83d875c7f6fb8b9dd9348cf4ec811a6";
      sha256 = "0n1ch69xfzqxggxv92s24mx72li39d09wjfw6fx3v8nqpg6xmbam";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b533 = let
    args = {
      version = "533";
      rev = "71e8b1e288b1427c32ff9debd99d623e633358b3";
      sha256 = "174j4y361xj6f2ahskzd8qxa0hxz8lqx40ix7ml505a2a9p91qyy";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b530 = let
    args = {
      version = "530";
      rev = "ccbeb794f0a5f0b2a46decb6c42a14ad24681c04";
      sha256 = "1rhbqi7nwam96dd3yn3grvlyf3l2dnxgjpm4g7x12zrlwlwy8brr";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b527 = let
    args = {
      version = "527";
      rev = "1e1cf062ecb3953b46940b4af4a755a538d8b304";
      sha256 = "0zc8dfnn90wxss5m20xgg36vh0sidz3pf4cjw2jwpxsylbf88pvm";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
  b525 = let
    args = {
      version = "525";
      rev = "d64ab1e006d04980449c0928df7aac040668b0d5";
      sha256 = "1ckmsca1f0qvsw1ja7m4l91x5m1a5k7asq8hv1szkyi9f08pyybr";
    };
  in with cataclysmBN; {
    tiles = attachPkgs pkgs (common.tiles.override args);
    curses = attachPkgs pkgs (common.curses.override args);
  };
}
