# Automatically generated by `update-jenkins.scm`. DO NOT EDIT!
{ cataclysmDDA }:

rec {
  latest = b11164;
  b11164 = let
    args = {
      version = "jenkins-b11164";
      rev = "64b8950ada59d590485c769e3926cdc32f337fff";
      sha256 = "009hz26lb2r6anc7c9w321w9bbbwvka6jy7f5s7bnllgfy7x5aab";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11163 = let
    args = {
      version = "jenkins-b11163";
      rev = "03098167f563c5e208dd8ab8d469df75318afeaa";
      sha256 = "09q6ngwijr807bxcbwka1byg1iq1dw93dqx662b0n5f2984i8p4d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11162 = let
    args = {
      version = "jenkins-b11162";
      rev = "a2c084df0ea9657e4af5749fa2d0451e8f250c34";
      sha256 = "1f4zv72babz5fzfz7vx38ncnnk05q23787pnrf31dlaprpfyp52d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11161 = let
    args = {
      version = "jenkins-b11161";
      rev = "938a274e93f37440de346a24165bb2ee6889640f";
      sha256 = "1h44vzdhpvz1xf5j34jzn2zpb16aljwsd9v8zpncf5v3k4kdbark";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11160 = let
    args = {
      version = "jenkins-b11160";
      rev = "0a99e8675abfc7337d3c171912a14c137738e915";
      sha256 = "124pnvvqki14cxwzzrh7rmrylmywl9a9whnbhflhws529vcp8c4a";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11159 = let
    args = {
      version = "jenkins-b11159";
      rev = "bcdd3a2561a09cf40546c8df53585937688e823a";
      sha256 = "0bg74cg72ybpqp53xw3vpi0idfy821yp501qa9941lp2kfl1lf22";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11158 = let
    args = {
      version = "jenkins-b11158";
      rev = "b48a96752f181f02aa3da654055954a8aa0e5d50";
      sha256 = "1gjbs7flk88kaqls53qfhr0ad8rzbl1wwci88amnq9yh7l62fqad";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11157 = let
    args = {
      version = "jenkins-b11157";
      rev = "48b6f14a33b1639e3992430df515396ad5340fa0";
      sha256 = "135cv2mhji287xwsnj7w3ihd8m8k607biv8avj9c6m4qhjr55app";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11156 = let
    args = {
      version = "jenkins-b11156";
      rev = "c78f54f98534ae1deaafdacc10b741d1fd1404c7";
      sha256 = "1a2yag165y9ab34vzixyllmkyqbkf4dfqd8bhwgpjl2rcib62sx2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11155 = let
    args = {
      version = "jenkins-b11155";
      rev = "b285a130801aee625fa888df27382e843bf12f84";
      sha256 = "0n24w2w7fip5jchqfcsrkn34bp1i619vczpg8qmbv2ywzkpd3qh4";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11154 = let
    args = {
      version = "jenkins-b11154";
      rev = "34527a6497d07547a20317feaacd3fac7da4b82c";
      sha256 = "1m0q7dbkyddrxxs4laj1nna1vfzadamb7jnmgd121vmm9zp4m2xf";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11153 = let
    args = {
      version = "jenkins-b11153";
      rev = "7f7deed9372da80f2f169e65ebb7a636a5fea0be";
      sha256 = "1pk32x38pfrf7x7syy6s5cimb97ydr782hayv70n5flwwbbilv0g";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11152 = let
    args = {
      version = "jenkins-b11152";
      rev = "524cacb9347c302344d161e0239277def693e7a2";
      sha256 = "1bclnjh9l14wyfkh1fs0hmfas32arkirqmd81wnvqsy9djhzi9n3";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11151 = let
    args = {
      version = "jenkins-b11151";
      rev = "895bbd8aa9d77691a50a5a1296b4be2ec262931a";
      sha256 = "061lgfykknvyrzc1hhjy78i32wqwn21fgdwrasx1hwh8h8qs8hi2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11150 = let
    args = {
      version = "jenkins-b11150";
      rev = "cbcf5fd9bd75d1368500aafa51676defb7f4affc";
      sha256 = "0km9gdxb45kslp672syhzhnnl4yh16lvijzyqvappkgshc3g3wmk";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11149 = let
    args = {
      version = "jenkins-b11149";
      rev = "a726b44c131b95f0626c47625dd0099113de398f";
      sha256 = "0c9n6ghh4yjma9n4lh7608g4df2kpspv04gync38cb6lpjdfnfjg";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11147 = let
    args = {
      version = "jenkins-b11147";
      rev = "246764612731c35bb50d8d6f6ff3bac4921cdc72";
      sha256 = "1ibq4sf193iy4wls74zibd2n9zk3zqarnfja9lymm3nb3ynbbn2d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11146 = let
    args = {
      version = "jenkins-b11146";
      rev = "d10f768cdba15dd6a42d17be5bdc1514d883bb5d";
      sha256 = "04hlycla5k00karqf62rya5hjy0yncr4azlrpw9diyia2l9n6ixq";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11145 = let
    args = {
      version = "jenkins-b11145";
      rev = "891488a81bd58099a8d7b852b519bc06ee121616";
      sha256 = "0bd0si1pmmzjcp45kndwal29v88xwcnd3lqxisbr4k6c0snqxr1g";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11144 = let
    args = {
      version = "jenkins-b11144";
      rev = "86a33cec95be8d28b67726a43adb1186945a7ed5";
      sha256 = "1g5cmqn2dlgv7y7b816vbp3k6c9gp4d4k6qlhy6kqvgn2kssprc0";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11143 = let
    args = {
      version = "jenkins-b11143";
      rev = "d9c3237d0a5758a48986d8f7edb41bc2830aa524";
      sha256 = "17c4qxrbncq5jzyff0azk7kxrmvdsznmc5f7kdq5y0di6bjb8514";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11142 = let
    args = {
      version = "jenkins-b11142";
      rev = "967d80c518e6ea9519c6d4f4c7d6d0749fc54408";
      sha256 = "0p9c8403jlg0z3cc35mpr4399j9pfpky2qlwghvgf4jqjgjyxygg";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11141 = let
    args = {
      version = "jenkins-b11141";
      rev = "146d314a699f2225eefa87905cd6db4edaec5650";
      sha256 = "0ybh3vvsxv7yfk40cpcrp2drwgyph7mdijlmkplxy80j3q78bw6v";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11140 = let
    args = {
      version = "jenkins-b11140";
      rev = "f3904702a0c4c3ca5a065aac5171838942a85dde";
      sha256 = "1y53nj1531l6zwjk3c4sjcb8kh0hwsqasl0w3ifhmw0ijdbza9nx";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11139 = let
    args = {
      version = "jenkins-b11139";
      rev = "20d1078faeb20662134239137571a6621102d864";
      sha256 = "19ppy2ild5rk79v5zwdlgvl36k6d8byim15ahyqvvq84hjz4gch2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11138 = let
    args = {
      version = "jenkins-b11138";
      rev = "7e2d62f0116676b88ffa2e52c1fd63ad4a63d163";
      sha256 = "1n2g6843856yv8sslhia6074pdmdwjpprxna0mp6php7wa5kkpkv";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11137 = let
    args = {
      version = "jenkins-b11137";
      rev = "63860a4305dbdd3cc90ec31b668cf9803836b5a8";
      sha256 = "1qhi65fd76l0j6asyaakyr55qpvxm57rnr186bmhs8s9q574cxvw";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11136 = let
    args = {
      version = "jenkins-b11136";
      rev = "1f4fa29988df316a2f61d0c4edd07019877e0591";
      sha256 = "0rbzm26kdmy7994n1sb527q7gmrm9i642gnrma3367rky6av3nc1";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11135 = let
    args = {
      version = "jenkins-b11135";
      rev = "d44542cb44b6acc16e82a01d7007a2e26dd3b291";
      sha256 = "189051v05mpxzjw89dvhkh3mkkvqm33y8zh4dv8jlbi498d35m00";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11134 = let
    args = {
      version = "jenkins-b11134";
      rev = "61d7a545ca78b83f56da8b74e06c3f2def9bc9f4";
      sha256 = "082q0slvg1zf45qipzcx72445rlgyx2a29z4gyfs72kbnlvryylf";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11133 = let
    args = {
      version = "jenkins-b11133";
      rev = "b71918da2f1b0ac685de7f4143b81757bae59c05";
      sha256 = "16zm6lgjx50gxzf6hrdx9s1lxii5xcxb5pn79qasrlwghfn6yihk";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11132 = let
    args = {
      version = "jenkins-b11132";
      rev = "b165e2115112646ee6779c97980045654b77fc53";
      sha256 = "1564zy0wad1jp1pcnlksi5bg4y31p6lnxbbv6lwcj2aqabsip7ci";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11131 = let
    args = {
      version = "jenkins-b11131";
      rev = "f5bd4da9ef9ffff89cf14d56491314e139ae5df9";
      sha256 = "0wp96z31dv4zx49rpcj0mg40qqyx4rqvks3mqsiv9wbkb1q0hdw0";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11130 = let
    args = {
      version = "jenkins-b11130";
      rev = "ee0a92cae25e3dfc876e1a67d198c3b669d7c68e";
      sha256 = "0byhpnh8xsq9v8gzw4246zvxhjv2b40cx1kq54n7l2d52hciin4x";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11129 = let
    args = {
      version = "jenkins-b11129";
      rev = "96ccece64330f50dac435182ad7c3afe2e42423c";
      sha256 = "1nr4hki5yla4jkvs6b08cazqlimkcdl6dd26y7yln2zydinq4p5l";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11128 = let
    args = {
      version = "jenkins-b11128";
      rev = "e5383cc8cbe9ddfdac91b4547b4f236c80cb6d17";
      sha256 = "0dj3wr8kf81lzbzrcgnn7l9yjhzh2gbgwjk2a4nc2gybfkz35j0s";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11127 = let
    args = {
      version = "jenkins-b11127";
      rev = "cf67157d32607326fee0cffd6739f091cf193224";
      sha256 = "13s4vxfr5f63zm95kpn9x2fz3bmh43l9ryksk546k2l8367ang6f";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11126 = let
    args = {
      version = "jenkins-b11126";
      rev = "fc2388e53c689e516ea9ff1e90f1cf55005b9b39";
      sha256 = "0fkf2glanlqa6a8sx7qkain55ywi0ccnjm2hq2pi6ysk0fkxi92c";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11125 = let
    args = {
      version = "jenkins-b11125";
      rev = "db48f0ce6c7d9d4eac58967d14d2b7680be1c912";
      sha256 = "05rqlqr2q007ydsd96lxs8ghcjys549n8sllfskydz1x3fr4765s";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11124 = let
    args = {
      version = "jenkins-b11124";
      rev = "a372128fcde414584dda13945c41c2e30ac4768b";
      sha256 = "0f3bim07iqd18i7irkjvnq6sqywz5dsfdliy0q3fqzk16z7x7k0c";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11123 = let
    args = {
      version = "jenkins-b11123";
      rev = "1ae4a801c44e991fbd82eea8f91edf2311d83838";
      sha256 = "0m0rni8bx8njqzi21fna3lwvmjknkds8c869xb5djbm4is1wzam7";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11122 = let
    args = {
      version = "jenkins-b11122";
      rev = "1238d8c1986d98c4366afeb1ab7f3afed07e325d";
      sha256 = "11raphii0qgbgmjz6r0hazh3dydfjass5hk0gy4zfrfjw4xcg30z";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11121 = let
    args = {
      version = "jenkins-b11121";
      rev = "ee5753246748653c93cfaecbda982d63ec4210ce";
      sha256 = "0wc9vac2h0gamzn3a9ggrmq3qqrsw5zd2fxmqz8p1vg2h47gjifh";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11120 = let
    args = {
      version = "jenkins-b11120";
      rev = "56c20114ead4d6a6d4c9621e00577504329637bb";
      sha256 = "0f6lxpcjpdgyg6jw42c1ci1nm47vid9l51hvz096ki3dlnmfdhr8";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11119 = let
    args = {
      version = "jenkins-b11119";
      rev = "19c792191b80cce534bf1c8fbd615b5dce5c79d9";
      sha256 = "00rmj63zhxg9kfyhxffjn2px6r0chwal4nghn4pafwlpyal2720q";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11118 = let
    args = {
      version = "jenkins-b11118";
      rev = "00daf3ad7a444b08a558a0b0f1f3d292da433247";
      sha256 = "17yqdb9d4d55rqhvi5czrymppb67gdx4mfwf8vf5q8y93ya07j9s";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11117 = let
    args = {
      version = "jenkins-b11117";
      rev = "db7d1378fa53326111c08c5fd9d2a336c779bf95";
      sha256 = "0n1rcqvqkcn03h511ldg7giya2lzyrv8qa159iivjhkk54668f29";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11116 = let
    args = {
      version = "jenkins-b11116";
      rev = "fc4a2a831fac967c236c5fa8325e4996fb87407b";
      sha256 = "0l0wp0gb2ag3ysr9m9pzc0indqyw8fswmpwcnpynk3ns9735v40n";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11115 = let
    args = {
      version = "jenkins-b11115";
      rev = "dff5e4e601ecccf133841aa85748ac929bb437d1";
      sha256 = "1ckg97zz82psppjnjbrimayqg6k8zdvb909h2i2wa8ds05gw5yfc";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11114 = let
    args = {
      version = "jenkins-b11114";
      rev = "87ee0ffbf9123adc24108ce4bbd3d0ed6efba74d";
      sha256 = "0qagzx60mi820cbmn8f4s89xvlcrw3ngzp60ws2y7f6r1cna8cv8";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11113 = let
    args = {
      version = "jenkins-b11113";
      rev = "17557d45ce12eda92e5db3ed7c34c8038281b28e";
      sha256 = "0ax0gg4bgig94rc90hhcd39h5x6x2yvyj39wv23bi6rpfajcam8r";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11112 = let
    args = {
      version = "jenkins-b11112";
      rev = "f8d184a866d116ca52bfc57ab6d368e406e2853b";
      sha256 = "0zfpsfibknkmnyb6g7fffbswx0m174k1jl9vyhnihkss157glhmk";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11111 = let
    args = {
      version = "jenkins-b11111";
      rev = "f3223015289f043bf33aae8a21882d276e306604";
      sha256 = "18m7rsrqxfp4fa7jadbrh7f0szjmrp016ws6zil8dj6zrfc31f6v";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11110 = let
    args = {
      version = "jenkins-b11110";
      rev = "a6b7ead892615a9685ad796cb3b3e22217441e00";
      sha256 = "0m6fabgzfa7cl4psx3gx2y3k0npygcps4h0di9gvnvc3bkhnp74g";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11109 = let
    args = {
      version = "jenkins-b11109";
      rev = "2c04d796ef877401053439d9ffecfcaa96bc5b2e";
      sha256 = "1lqa1x6ikykhqnwmh282r6szf3mkpfsbmgg4pxxymnj17pdabd1h";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11108 = let
    args = {
      version = "jenkins-b11108";
      rev = "80909092ecb363e011fd336b4795f62d90cb9bce";
      sha256 = "1iiiy1a4ai6n7kvpwajpxdzfq86ny75skls4xz19qa7v5lalhd4d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11107 = let
    args = {
      version = "jenkins-b11107";
      rev = "6fb2e4999e602ee704b1409676e0960565a9b2fe";
      sha256 = "1hjc1a7xai60w87s53rpyz3nyrs6w5p3x456lqbhgvy3lcfmf8dy";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11106 = let
    args = {
      version = "jenkins-b11106";
      rev = "7ff5d4195fcb2796668ba24f714e3d9a5644be04";
      sha256 = "0mkx7n5z1k129jhpr090b6vpf31i2ihyzj1mzm1xlsl11f11r55d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11105 = let
    args = {
      version = "jenkins-b11105";
      rev = "5f382961f97f292595be69998fb88dbe914c2d70";
      sha256 = "0a1j1mh2b6xbbns5k07afp4m6hdclrv3ghlx11qd6dgjpp62f5gn";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11104 = let
    args = {
      version = "jenkins-b11104";
      rev = "8c33cbe7daf69976131a48be33f03014c976caa1";
      sha256 = "16fi3hrrmzkxk9z0qjhjga3s2mky1i6vmy5xgilmsc2dw3ab87p6";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
}
