# Automatically generated by `update-jenkins.scm`. DO NOT EDIT!
{ cataclysmDDA }:

rec {
  latest = b11197;
  b11197 = let
    args = {
      version = "jenkins-b11197";
      rev = "534b4dd690ec3ec4dbfef07880c49f0f31a0ce7d";
      sha256 = "1x17pw17qlxp5iqnlp61il47hikf8bpqzkvc87par5cprl341nab";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11196 = let
    args = {
      version = "jenkins-b11196";
      rev = "f780ab97238ca35232a257f5554ad5b87bf83a41";
      sha256 = "0xxg041cqshbp0iijgblvhp80qs2p6pkxalis6360qchl37s856l";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11195 = let
    args = {
      version = "jenkins-b11195";
      rev = "f780ab97238ca35232a257f5554ad5b87bf83a41";
      sha256 = "0xxg041cqshbp0iijgblvhp80qs2p6pkxalis6360qchl37s856l";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11194 = let
    args = {
      version = "jenkins-b11194";
      rev = "f780ab97238ca35232a257f5554ad5b87bf83a41";
      sha256 = "0xxg041cqshbp0iijgblvhp80qs2p6pkxalis6360qchl37s856l";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11193 = let
    args = {
      version = "jenkins-b11193";
      rev = "bddb708d67d8af8df95c6ddc18ae9760beb52c2c";
      sha256 = "064xhk4dg8cavzzxs6hvkv13bk8xcn6qb6z80pfjnx49401385w6";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11192 = let
    args = {
      version = "jenkins-b11192";
      rev = "76fd581d432bdd17fb6817e4592c0252e1bb9f34";
      sha256 = "1c9vdigrra7z4dnxz75bj3qpk9r169b52l8ax936p4yshnzri5ny";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11190 = let
    args = {
      version = "jenkins-b11190";
      rev = "df17a62d10340a24a987b41ccc8203a221e16a30";
      sha256 = "11za9i7r4rafhsmlfi8w7jq3fv85yii1sbk62rjzq1wc0k8ig33f";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11189 = let
    args = {
      version = "jenkins-b11189";
      rev = "91561ac078f876f3fd98acc699f6b9d388100186";
      sha256 = "0is5cnh0g9xwlkzikjxaqikfim4ih17dx1h9jr8n9hgrrc3wab3f";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11188 = let
    args = {
      version = "jenkins-b11188";
      rev = "a66cf5280b85ba488aaa276cffde165ba44a052f";
      sha256 = "0v15qg7v4q8j27cqm39im7i8sy9cack68c2kdij0phxgh6ml3ygs";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11187 = let
    args = {
      version = "jenkins-b11187";
      rev = "26d2ef6ca2131608232c71927b1fce1b7173f915";
      sha256 = "05b1bs5k62lpb5lhj04s9l6k0if0nnvsbaaivwk2yjwd2l7j06pk";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11186 = let
    args = {
      version = "jenkins-b11186";
      rev = "7c1533deb609007a79649c4a22c19f1bbff1bd96";
      sha256 = "038jg6wglvr7f0msm5vxljikcpnhs5qhrid1z8wjc9crf0k0nkfv";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11185 = let
    args = {
      version = "jenkins-b11185";
      rev = "e8b894a0e4630cb4ec7fb77e2387cfe9564b2e9b";
      sha256 = "16c41m1sa47072ca911abjcrqy5yp4w8bx1ypz7sh77hq27hdvzj";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11184 = let
    args = {
      version = "jenkins-b11184";
      rev = "98d7868836b9fa6e58e9c61518795b09258f4551";
      sha256 = "05f4qnvinfdk10if0qin0ps1ps6qynj69zr5nk4qwjvmg3h7l0jm";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11183 = let
    args = {
      version = "jenkins-b11183";
      rev = "df54339b4bce5e354002f2a5a2366d1722a4cb7f";
      sha256 = "1w2jzfa0wk6wn6r85f7czch7ny4z0p1ms56m2l5qzq8zm9fpm32w";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11182 = let
    args = {
      version = "jenkins-b11182";
      rev = "eabce95ab099428e5509f12823ab11db2d4e2eb1";
      sha256 = "1lyh9x6gnnjfpp1bg45lqb7x93nf7k8iinv3wmhncxpwdhbraxii";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11181 = let
    args = {
      version = "jenkins-b11181";
      rev = "f3a1933ee8bb786ba44caa2b40af582f4901281d";
      sha256 = "17cbyc1zx7clylnpysfqmgar3bnd7r3zlngqkwiymb54pfhkwdnp";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11180 = let
    args = {
      version = "jenkins-b11180";
      rev = "f3a1933ee8bb786ba44caa2b40af582f4901281d";
      sha256 = "17cbyc1zx7clylnpysfqmgar3bnd7r3zlngqkwiymb54pfhkwdnp";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11179 = let
    args = {
      version = "jenkins-b11179";
      rev = "55fac0a69d86b4b51a5d3299e8ecc80f37032f67";
      sha256 = "0qwkl1cmwykd6kxr8z8af78hd3slvgb4ql91klig70350r7f11hh";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11178 = let
    args = {
      version = "jenkins-b11178";
      rev = "c6324c0ec70a9a9745db8a6a675371afd7d91e2f";
      sha256 = "062rc69r8wg3rpdcmzz9ykbv7lwcp4vx00wwa3xbfjrc3qjvqbdw";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11177 = let
    args = {
      version = "jenkins-b11177";
      rev = "d4a0263c47860e87a298b9d0ae7eed3c7b6a2646";
      sha256 = "1jif2b55wl92cmr7kn4lnlw09958q9vwyagy0l5kc4xh1cq9fca4";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11176 = let
    args = {
      version = "jenkins-b11176";
      rev = "6bc32965b2d4c7bd95f64ae7f42811258c588fab";
      sha256 = "1if5q8cpi4caxikn1vyzxps9jkjbb0d8q0knhj00d700rk9bmj0c";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11175 = let
    args = {
      version = "jenkins-b11175";
      rev = "38716182a41a26b61816b2d32072e52c969ec738";
      sha256 = "1xpzdzzvgfgzcak4k1bcwrpj8ma8wzjc7djas2854l2bg7ygnycm";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11174 = let
    args = {
      version = "jenkins-b11174";
      rev = "ac49e4099046dc9a3481f99c3b4fffc4be5115f0";
      sha256 = "13k9g6rvdaglhqnn0am1gmqmd080f3xbsyav0sml0y4fbdahsdyn";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11173 = let
    args = {
      version = "jenkins-b11173";
      rev = "1e0c90ea691bda49941f69969deb0d5f9d814d49";
      sha256 = "1i1d5hbld5q7whhi4q5nf14r7m7s2lm60hw5aaxq51hskq3mjglb";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11172 = let
    args = {
      version = "jenkins-b11172";
      rev = "c764d46aac54e9bf2a7a7d52ab244373e6cdd876";
      sha256 = "1r05h7q5bdwazgdd4f0f48r4w356vhl1laaa9aznhlvwvz6qs4pj";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11171 = let
    args = {
      version = "jenkins-b11171";
      rev = "ca9b8c1005aa504f00ce4f42ffbe0e8d15240e2d";
      sha256 = "077my9aj2qknva8scg40dy31nkmmxq3c5p4vx650pdz0sb3m54rw";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11170 = let
    args = {
      version = "jenkins-b11170";
      rev = "4f7bfb505bf4ab9c63577f9c0f1f0ae0ecb2cadf";
      sha256 = "1jqgkd9yyw49yffhpikkbm09zj4909kk5v3623vc1y81qgm0k2jm";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11169 = let
    args = {
      version = "jenkins-b11169";
      rev = "6c46204112c6ff032fe5b81ff5a7597dd63591f3";
      sha256 = "0jvi527lbhxbynr7zr575z1vgr35cncanyyv9r9drv899011kfpz";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11168 = let
    args = {
      version = "jenkins-b11168";
      rev = "8d87f156b966b53a4dd5ae3e1bcc4dfbccb67685";
      sha256 = "0xrqii196w0l6mrbhmmqb8sspcxm3mwrdna86ckmwgnk9q2r6pg6";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11167 = let
    args = {
      version = "jenkins-b11167";
      rev = "24470a32f18acfa82d08b1d9020a7563a507301e";
      sha256 = "06ns5qv4pxdrbcm17czv2vipjaahss5763nybp454d44jj18k6yz";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11166 = let
    args = {
      version = "jenkins-b11166";
      rev = "532b9fe42a5cf2c6002defaeadb02284e414301c";
      sha256 = "1wlhgm920q5gjga66v4ryy7jnr7zy1l2cjsx8kl2sykn652dq0hz";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11165 = let
    args = {
      version = "jenkins-b11165";
      rev = "165a25c8cb967d6a4dc2aa55f89cd6d49f4e09ae";
      sha256 = "03wf0b3hxc3kwh2hiyl6rs32lwr3h4bbfm9bkp47x8qxaqbsgjjd";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11164 = let
    args = {
      version = "jenkins-b11164";
      rev = "64b8950ada59d590485c769e3926cdc32f337fff";
      sha256 = "009hz26lb2r6anc7c9w321w9bbbwvka6jy7f5s7bnllgfy7x5aab";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11163 = let
    args = {
      version = "jenkins-b11163";
      rev = "03098167f563c5e208dd8ab8d469df75318afeaa";
      sha256 = "09q6ngwijr807bxcbwka1byg1iq1dw93dqx662b0n5f2984i8p4d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11162 = let
    args = {
      version = "jenkins-b11162";
      rev = "a2c084df0ea9657e4af5749fa2d0451e8f250c34";
      sha256 = "1f4zv72babz5fzfz7vx38ncnnk05q23787pnrf31dlaprpfyp52d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11161 = let
    args = {
      version = "jenkins-b11161";
      rev = "938a274e93f37440de346a24165bb2ee6889640f";
      sha256 = "1h44vzdhpvz1xf5j34jzn2zpb16aljwsd9v8zpncf5v3k4kdbark";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11160 = let
    args = {
      version = "jenkins-b11160";
      rev = "0a99e8675abfc7337d3c171912a14c137738e915";
      sha256 = "124pnvvqki14cxwzzrh7rmrylmywl9a9whnbhflhws529vcp8c4a";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11159 = let
    args = {
      version = "jenkins-b11159";
      rev = "bcdd3a2561a09cf40546c8df53585937688e823a";
      sha256 = "0bg74cg72ybpqp53xw3vpi0idfy821yp501qa9941lp2kfl1lf22";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11158 = let
    args = {
      version = "jenkins-b11158";
      rev = "b48a96752f181f02aa3da654055954a8aa0e5d50";
      sha256 = "1gjbs7flk88kaqls53qfhr0ad8rzbl1wwci88amnq9yh7l62fqad";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11157 = let
    args = {
      version = "jenkins-b11157";
      rev = "48b6f14a33b1639e3992430df515396ad5340fa0";
      sha256 = "135cv2mhji287xwsnj7w3ihd8m8k607biv8avj9c6m4qhjr55app";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11156 = let
    args = {
      version = "jenkins-b11156";
      rev = "c78f54f98534ae1deaafdacc10b741d1fd1404c7";
      sha256 = "1a2yag165y9ab34vzixyllmkyqbkf4dfqd8bhwgpjl2rcib62sx2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11155 = let
    args = {
      version = "jenkins-b11155";
      rev = "b285a130801aee625fa888df27382e843bf12f84";
      sha256 = "0n24w2w7fip5jchqfcsrkn34bp1i619vczpg8qmbv2ywzkpd3qh4";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11154 = let
    args = {
      version = "jenkins-b11154";
      rev = "34527a6497d07547a20317feaacd3fac7da4b82c";
      sha256 = "1m0q7dbkyddrxxs4laj1nna1vfzadamb7jnmgd121vmm9zp4m2xf";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11153 = let
    args = {
      version = "jenkins-b11153";
      rev = "7f7deed9372da80f2f169e65ebb7a636a5fea0be";
      sha256 = "1pk32x38pfrf7x7syy6s5cimb97ydr782hayv70n5flwwbbilv0g";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11152 = let
    args = {
      version = "jenkins-b11152";
      rev = "524cacb9347c302344d161e0239277def693e7a2";
      sha256 = "1bclnjh9l14wyfkh1fs0hmfas32arkirqmd81wnvqsy9djhzi9n3";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11151 = let
    args = {
      version = "jenkins-b11151";
      rev = "895bbd8aa9d77691a50a5a1296b4be2ec262931a";
      sha256 = "061lgfykknvyrzc1hhjy78i32wqwn21fgdwrasx1hwh8h8qs8hi2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11150 = let
    args = {
      version = "jenkins-b11150";
      rev = "cbcf5fd9bd75d1368500aafa51676defb7f4affc";
      sha256 = "0km9gdxb45kslp672syhzhnnl4yh16lvijzyqvappkgshc3g3wmk";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11149 = let
    args = {
      version = "jenkins-b11149";
      rev = "a726b44c131b95f0626c47625dd0099113de398f";
      sha256 = "0c9n6ghh4yjma9n4lh7608g4df2kpspv04gync38cb6lpjdfnfjg";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11147 = let
    args = {
      version = "jenkins-b11147";
      rev = "246764612731c35bb50d8d6f6ff3bac4921cdc72";
      sha256 = "1ibq4sf193iy4wls74zibd2n9zk3zqarnfja9lymm3nb3ynbbn2d";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11146 = let
    args = {
      version = "jenkins-b11146";
      rev = "d10f768cdba15dd6a42d17be5bdc1514d883bb5d";
      sha256 = "04hlycla5k00karqf62rya5hjy0yncr4azlrpw9diyia2l9n6ixq";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11145 = let
    args = {
      version = "jenkins-b11145";
      rev = "891488a81bd58099a8d7b852b519bc06ee121616";
      sha256 = "0bd0si1pmmzjcp45kndwal29v88xwcnd3lqxisbr4k6c0snqxr1g";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11144 = let
    args = {
      version = "jenkins-b11144";
      rev = "86a33cec95be8d28b67726a43adb1186945a7ed5";
      sha256 = "1g5cmqn2dlgv7y7b816vbp3k6c9gp4d4k6qlhy6kqvgn2kssprc0";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11143 = let
    args = {
      version = "jenkins-b11143";
      rev = "d9c3237d0a5758a48986d8f7edb41bc2830aa524";
      sha256 = "17c4qxrbncq5jzyff0azk7kxrmvdsznmc5f7kdq5y0di6bjb8514";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11142 = let
    args = {
      version = "jenkins-b11142";
      rev = "967d80c518e6ea9519c6d4f4c7d6d0749fc54408";
      sha256 = "0p9c8403jlg0z3cc35mpr4399j9pfpky2qlwghvgf4jqjgjyxygg";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11141 = let
    args = {
      version = "jenkins-b11141";
      rev = "146d314a699f2225eefa87905cd6db4edaec5650";
      sha256 = "0ybh3vvsxv7yfk40cpcrp2drwgyph7mdijlmkplxy80j3q78bw6v";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11140 = let
    args = {
      version = "jenkins-b11140";
      rev = "f3904702a0c4c3ca5a065aac5171838942a85dde";
      sha256 = "1y53nj1531l6zwjk3c4sjcb8kh0hwsqasl0w3ifhmw0ijdbza9nx";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11139 = let
    args = {
      version = "jenkins-b11139";
      rev = "20d1078faeb20662134239137571a6621102d864";
      sha256 = "19ppy2ild5rk79v5zwdlgvl36k6d8byim15ahyqvvq84hjz4gch2";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11138 = let
    args = {
      version = "jenkins-b11138";
      rev = "7e2d62f0116676b88ffa2e52c1fd63ad4a63d163";
      sha256 = "1n2g6843856yv8sslhia6074pdmdwjpprxna0mp6php7wa5kkpkv";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11137 = let
    args = {
      version = "jenkins-b11137";
      rev = "63860a4305dbdd3cc90ec31b668cf9803836b5a8";
      sha256 = "1qhi65fd76l0j6asyaakyr55qpvxm57rnr186bmhs8s9q574cxvw";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
  b11136 = let
    args = {
      version = "jenkins-b11136";
      rev = "1f4fa29988df316a2f61d0c4edd07019877e0591";
      sha256 = "0rbzm26kdmy7994n1sb527q7gmrm9i642gnrma3367rky6av3nc1";
    };
  in with cataclysmDDA; {
    tiles = attachPkgs pkgs (git.tiles.override args);
    curses = attachPkgs pkgs (git.curses.override args);
  };
}
