#!/usr/bin/env gosh

(use file.util)
(use gauche.collection)
(use github)
(use nix-prefetch)
(use rfc.tls)
(use srfi-13)

;; Because there are thousands of jenkins build tags, we limit the number of builds to keep.
(define-constant *builds-to-keep* 60)

(define (%generate-nix-expr tag&rev :optional (indent 2))
  (let* ([tag (car tag&rev)]
         [rev (cdr tag&rev)]
         [version (rxmatch-substring (#/(?<=cdda-)jenkins-b\d+/ tag))]
         [build-number (rxmatch-substring (#/(?<=cdda-jenkins-)b\d+/ tag))]
         [sha256 (nix-prefetch-url/cache!
                   #"https://github.com/CleverRaven/Cataclysm-DDA/archive/~|rev|.tar.gz"
                   :unpack? #t
                   :name #"cataclysm-dda-git-~|version|")]
         [lines `(,#"~|build-number| = let"
                  "  args = {"
                  ,#"    version = \"~|version|\";"
                  ,#"    rev = \"~|rev|\";"
                  ,#"    sha256 = \"~|sha256|\";"
                  "  };"
                  "in {"
                  "  tiles = with cataclysmDDA; updatePkgs (git.tiles.override args);"
                  "  curses = with cataclysmDDA; updatePkgs (git.curses.override args);"
                  "};")])
    (string-join (map (pa$ string-append (make-string indent #\ )) lines) "\n")))

(define (generate-nix-exprs tags)
  (let1 latest (rxmatch-substring (#/(?<=cdda-jenkins-)b\d+/ (caar tags)))
    (string-join `("# Automatically generated by `update-jenkins.scm`. DO NOT EDIT!"
                   "{ cataclysmDDA }:\n\nrec {"
                   ,#"  latest = ~|latest|;"
                   ,@(map %generate-nix-expr tags)
                   "}")
                 "\n")))

(define (main _)
  (default-tls-class <mbed-tls>)
  (load-sha256-cache!)
  (let1 tags (take (tree-map->alist (github-get-cdda-jenkins-tags))
                   *builds-to-keep*)
    (with-output-to-file (build-path "generated" "jenkins.nix")
                         (cut print (generate-nix-exprs tags))))
  (save-sha256-cache!)
  (exit))
