# Automatically generated by `update-mods.scm`. DO NOT EDIT!
{ lib, cataclysmDDA, fetchurl, fetchFromGitHub, unzip }:

{
  ArtyomsGunEmporium = cataclysmDDA.buildMod {
    modName = "ArtyomsGunEmporium";
    version = "2016-11-03";
    src = fetchurl {
      name = "ArtyomsGunEmporium-2016-11-03.zip";
      url = "https://www.dropbox.com/s/iudqj6ksnpo4i2r/Artyoms%27%20Gun%20Emporium.zip";
      sha256 = "02pja0sp7jj6sk29jq65jm5rnbh0vnlgfflr0p8ymcrk9y9q5jkr";
    };
    nativeBuildInputs = [ unzip ];
    meta = with lib; {
      homepage = "https://discourse.cataclysmdda.org/t/artyoms-gun-emporium-update-2-hotfix-1-holy-shit/10035/494";
    };
  };
  CataclysmPlusPlus = cataclysmDDA.buildMod {
    modName = "CataclysmPlusPlus";
    version = "2020-11-29";
    src = fetchFromGitHub {
      owner = "Noctifer-de-Mortem";
      repo = "nocts_cata_mod";
      rev = "c2d025213ccb3a0d543f6f2409dd6f77359a1faf";
      sha256 = "0znbcafa8cg4x2j5035zc2hla84jgmk4hdx44k0m8898r8y07wkr";
    };
    meta = with lib; {
      homepage = "https://discourse.cataclysmdda.org/t/cataclysm-mod/10523";
    };
  };
}
