# Automatically generated by `update-mods.scm`. DO NOT EDIT!
{ lib, cataclysmDDA, fetchurl, fetchFromGitHub, unzip }:

{
  UndeadPeople = cataclysmDDA.buildTileSet {
    modName = "UndeadPeople";
    version = "2020-11-12";
    src = fetchFromGitHub {
      owner = "SomeDeadGuy";
      repo = "UndeadPeopleTileset";
      rev = "bc1f59a53341394e004db26def2329860651ed04";
      sha256 = "0hzdxndx3mnqjsb4hbzs9qqmh1f3ifr1n6b5n1nx9whfc8lynmjq";
    };
    modRoot = "MSX++UnDeadPeopleEdition";
    meta = with lib; {
      homepage = "https://github.com/SomeDeadGuy/UndeadPeopleTileset";
    };
  };
}
