# Automatically generated by `update-mods.scm`. DO NOT EDIT!
{ lib, cataclysmDDA, fetchurl, fetchFromGitHub, unzip }:

{
  UndeadPeople = cataclysmDDA.buildTileSet {
    modName = "UndeadPeople";
    version = "2020-11-20";
    src = fetchFromGitHub {
      owner = "SomeDeadGuy";
      repo = "UndeadPeopleTileset";
      rev = "d1427d893ee54b4fd739ca6e6b76a3c8353e3be2";
      sha256 = "0pkbyr824iiwrqrwd6x4n0w8kjzyx61qn3c5fjiwd9mc2pf1yh7y";
    };
    modRoot = "MSX++UnDeadPeopleEdition";
    meta = with lib; {
      homepage = "https://github.com/SomeDeadGuy/UndeadPeopleTileset";
    };
  };
}
