# Automatically generated by `update-mods.scm`. DO NOT EDIT!
{ lib, cataclysmDDA, fetchurl, fetchFromGitHub, unzip }:

{
  UndeadPeople = cataclysmDDA.buildTileSet {
    modName = "UndeadPeople";
    version = "2020-11-18";
    src = fetchFromGitHub {
      owner = "SomeDeadGuy";
      repo = "UndeadPeopleTileset";
      rev = "3d25bfcea47a1ab0ffb225b3b7395ad313a4ede5";
      sha256 = "1ca7higjl7w2fdjd6hwhpbf2xydph5kc7gql7rp7rz3wa2ddjp9s";
    };
    modRoot = "MSX++UnDeadPeopleEdition";
    meta = with lib; {
      homepage = "https://github.com/SomeDeadGuy/UndeadPeopleTileset";
    };
  };
}
